/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { IAave } from "./IAave";

export class IAaveFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<IAave> {
    return super.deploy(overrides || {}) as Promise<IAave>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): IAave {
    return super.attach(address) as IAave;
  }
  connect(signer: Signer): IAaveFactory {
    return super.connect(signer) as IAaveFactory;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IAave {
    return new Contract(address, _abi, signerOrProvider) as IAave;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "onBehalfOf",
        type: "address",
      },
      {
        internalType: "uint16",
        name: "referralCode",
        type: "uint16",
      },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b5060a78061001e6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063e8eda9df14602d575b600080fd5b606960048036036080811015604157600080fd5b5080356001600160a01b0390811691602081013591604082013516906060013561ffff16606b565b005b5050505056fea26469706673582212202ab64a34362f074c45b4aadec1c0bf2ea52ecee2230a195c6fedc0c0952fed4864736f6c63430007060033";
